services:
  #Conteneur pour la base de données (db)
  db:
    image: postgis/postgis:16-3.4
    container_name: fenalim_db
    restart: unless-stopped
    #Informations de connexion pour la base de données
    environment:
      POSTGRES_USER: fenalim
      POSTGRES_PASSWORD: fenalim123
      POSTGRES_DB: fenalim_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fenalim_net
    ports:
      - "5432:5432"
  
  #Conteneur pour l'api
  api:
    build: ./backend
    container_name: fenalim_api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://fenalim:fenalim123@db:5432/fenalim_db
    #L'api dépend de la base de données
    depends_on:
      - db
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.fenalim.local`)"
      - "traefik.http.routers.api.entrypoints=web"
    networks:
      - fenalim_net
    volumes:
    - ./backend/app:/app/app

  #Conteneur pour pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: fenalim_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fenalim.fr
      PGADMIN_DEFAULT_PASSWORD: E03?M12/
    ports:
      - "5051:80"
    #pgadmin dépend de la base de données
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.fenalim.local`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
    networks:
      - fenalim_net

  # #Conteneur pour traefik. Pas encore mis en place (28/11/25), à retirer
  # traefik:
  #   image: traefik:v3.1
  #   container_name: traefik
  #   command:
  #     - "--api.dashboard=true"
  #     - "--providers.docker=true"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #   ports:
  #     - "80:80" #HTTP
  #     - "443:443" #HTTPS
  #     - "8080:8080" #localhost
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - fenalim_net

#Réseau commun pour tous les conteneurs
networks:
  fenalim_net:
    driver: bridge

volumes:
  db_data:
