FROM python:3.12-slim

WORKDIR /app

# Copier et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code
COPY . .

# Installer le package en mode éditable
RUN pip install -e .

# Forcer TESTING
ENV TESTING=true

# Vérifier que app est accessible
RUN python -c "import app.main; print('app.main found!')"

CMD ["pytest", "tests/", "-v", "--tb=short"]